//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;

public class GameProperties
{
	public static int top = 16;
	public static int bottom = -50;
	public static int left = -50;
	public static int right = 50;

	public static int padding = 5; // For random walks to always be reachable
	public static int topPadded { get { return top - padding;}}
	public static int bottomPadded { get { return bottom + padding;}}
	public static int leftPadded { get { return left + padding;}}
	public static int rightPadded { get { return right - padding;}}

	public static int height {
		get {
			return top - bottom;
		}
	}
	public static int width {
		get {
			return right - left;
		}
	}
	public static int initialLives = 3;
	public const int MAX_SHEEP = 20;
	public GameProperties ()
	{
	}
}
